import subprocess
import os
from datetime import datetime


class PDFToHTMLConverter:

    def __init__(self, docker_image: str):
        self.docker_image = docker_image

    def convert(self, input_pdf_path: str) -> str:
        # absolute path
        input_pdf_path = os.path.abspath(input_pdf_path)

        # folder + filename
        folder = os.path.dirname(input_pdf_path)
        filename = os.path.basename(input_pdf_path)

        # output file (auto-generated by pdf2htmlEX)
        output_html = filename.replace(".pdf", ".html")
        output_path = os.path.join(folder, output_html)

        # docker command
        cmd = [
            "docker", "run", "--rm",
            "-v", f"{folder}:/pdf",
            self.docker_image,
            "--zoom", "1.3",
            filename
        ]

        print("Running command:", " ".join(cmd))

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            raise Exception(f"Docker Error:\n{result.stderr}")

        if not os.path.exists(output_path):
            raise Exception("HTML file not generated")
        print(output_path)
        return output_path